### ISSUE TITLE
Cannot override user/icon/channel

### ISSUE THREAD

**Issue by RobertJBarron** [coursehero/slacktee#56]
Hello,

I think Slack has changed the way Incoming Webhooks work and they no longer allow customization of the message 
https://api.slack.com/incoming-webhooks#advanced_message_formatting
```You *cannot* override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.```

This makes some of the `slacktee` flags inoperative. Being able to control the channel is especially useful.

**Comment by Chikashi-Kato** [comment]
Ouch, this is a critical change for slacktee. Thank you for letting me know this, Robert.
I will test out the changes and update slacktee to address the changes.

**Comment by RobertJBarron** [comment]
From what I can see, keeping that functionality will mean changing from `incoming_webhook` to one of the web APIs.
Let me know if I can help :)

**Comment by Chikashi-Kato** [comment]
Thank you, Robert! I'm still testing on my end, but I still can specify 'channel', 'name' and 'icon' through webhook. Since the webhook I used for testing have created long time ago, Slack may be keeping the backward compatibility for old webhooks. 
I will create a new webhook and use it for my 2nd test.

It would be great if you can check when you created your webhook

**Comment by RobertJBarron** [comment]
Less than 24 hours before opening this issue.

**Comment by Chikashi-Kato** [comment]
Got it, thanks! I think Incoming Webhook with the legacy 'Custom Integration' still supports the overwrite for 'channel', 'name' and 'icon' parameters, but migrating to Slack App is highly recommended.

https://api.slack.com/custom-integrations/incoming-webhooks

I think it might be a time to migrate to Slack App from the custom integration. Also, as you mentioned, we may be using Web API instead of incoming webhook for overwriting 'channel', 'name' and 'icon'. Some features of slacktee are already using the API and the migration shouldn't be too too difficult, I believe.

I will start some research for the migration, but if you already have some implementation ideas in your mind, please drop them here!

**Comment by Chikashi-Kato** [comment]
Sorry for not posting an update for a while. I was busy in last 2 weeks and couldn't find a time to work on this issue. I am still trying to implement it by myself, but it would be really appreciated if anyone can submit a PR addressing this issue!

**Comment by Chikashi-Kato** [comment]
Add the logic posting messages through APIs and deprecated incoming webhook.
