### ISSUE TITLE
Using Webhook to run slacktee

### ISSUE THREAD

**Issue by micruzz82** [coursehero/slacktee#67]
Hi Team

I don't have access to a token but was only provided a webhook.

Whenever I run slacktee.sh after installation, I get 

slacktee.sh: Please setup the authentication token or the incoming webhook url (deprecated).

Can you please help me on how to configure the webhook url.

Thanks in advance.

**Comment by micruzz82** [comment]
found it in ~/.slacktee

**Comment by Chikashi-Kato** [comment]
@micruzz82 Sorry for not responding in a timely manner. I'm glad you could find the option.
Since Slack is deprecating webhook, we have removed the configuration from the documentation. 
Also, the latest version output the deprecation warning when you use webhook. 
If you don't want to see deprecation warning every time, please try to use v1.3.1.

Thank you for using slacktee!
