### ISSUE TITLE
Different output by same bot?

### ISSUE THREAD

**Issue by marcelo321** [coursehero/slacktee#74]
Hello,

I have a weird question. I have 2 vps and they print the output differently.

![imagen](https://user-images.githubusercontent.com/29487296/96683540-b16db300-1350-11eb-90f9-a1dff85b2c34.png)

As you can see, the first one has that line, and when reaching half the line, it goes to the second line, which is annoying as fuck.

my other bot prints it perfectly (last line of output).

In both of them I just tried `echo abc | slacktee -c channel`.

Any way to control this? or know why this is happening?

**Comment by marcelo321** [comment]
I don't want the blockquote that the bot is adding to the message. it ruins the output as everything is compacted, but I don't know how to delete it

**Comment by Chikashi-Kato** [comment]
Hi @marcelo321, thank you for using the slacktee.

For removing the line of the first bot's output, you need to disable `attachment`. Since you are not using `-a`/`--attachment` option, I'm assuming `attachment` variable in your `~/.slacktee` or `/etc/slacktee.conf` is NOT empty. Could you try to confirm it?
Here is the sample of `~/.slacktee`
```
webhook_url=""
token="your-token-here"
tmp_dir="/tmp"
channel="default-channel"
username="slacktee"
icon="ghost"
attachment=""
```

In order to remove the blockquote, please use `-p` or `--plain-text` option. 

I hope this helps

**Comment by marcelo321** [comment]
Thanks! it worked. I didn't know the .slacktee was in home directory so I was a bit confused.

Thanks again!
